### ISSUE TITLE
Error trying to decompress zip files in python 3

### ISSUE THREAD

**Issue by fedemotta** [fedemotta/subseek#2]
Text To Search: arrow s06e11 720p x264 hdtv
    Text To Match: subtitulo de arrow s06e11 de www tusubtitulo com para arrow s06e11 webrip ion10 y 720p 1080p amzn webrip casstudio en español españa
   Text Match (%): 68.01%
File downloaded
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/subseek/__main__.py", line 74, in <module>
    start(main)
  File "/usr/local/lib/python2.7/dist-packages/subseek/options.py", line 73, in start
    func(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/subseek/__main__.py", line 61, in main
    debug)
  File "/usr/local/lib/python2.7/dist-packages/subseek/utils.py", line 165, in best_subtitle_url
    min_match, force, debug)
  File "/usr/local/lib/python2.7/dist-packages/subseek/utils.py", line 152, in download_best_subtitle
    debug)
  File "/usr/local/lib/python2.7/dist-packages/subseek/utils.py", line 54, in download_subtitle
    search, force)
  File "/usr/local/lib/python2.7/dist-packages/subseek/models.py", line 277, in get_sub_file_from_file
    uncompressed_file, typefile = self.decompress_file(filename)
  File "/usr/local/lib/python2.7/dist-packages/subseek/models.py", line 254, in decompress_file
    uncompressed_file = rarfile.RarFile(filename)
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 666, in __init__
    self._parse()
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 856, in _parse
    raise BadRarFile("Not a RAR file")
rarfile.BadRarFile: Not a RAR file

**Comment by fedemotta** [comment]
Fixed in e5acf341637b7f2109d17a81478dd1cdc9c99b08
